// lib/identityPayload.ts

export const OPERATOR_IDENTITY = {
  metaphysical: {
    "Numerology": {
      lifePath: "22 (Master Builder) / Current: 11",
      coreArchetype: "The Flying Mountain",
      mode: "Jupiterian Rat",
      anchor: "9 Star Ki 8-8-2 Triple Earth",
    },
    "Starseed": {
      originPoint: "Adak, Alaska (Birthplace of the Winds)",
      masterSpiritualCourt: "Beleth (Sun/MC), Zagan (ASC)",
    },
  },
  culturalSystems: {
    "Cultural Systems": {
      chineseZodiac: { placement: "Yin Water Pig (1983)", meaning: "Functions as a stealth-capable fluid dynamics engine, absorbing and neutralizing hostile frequencies." },
      japanese: { placement: "TBD", meaning: "Awaiting Oracle Synthesis" },
      tzolkin: { placement: "TBD", meaning: "Awaiting Oracle Synthesis" },
      celticTree: { placement: "TBD", meaning: "Awaiting Oracle Synthesis" },
      decans: { placement: "TBD", meaning: "Awaiting Oracle Synthesis" },
      mahabote: { placement: "TBD", meaning: "Awaiting Oracle Synthesis" },
    },
  },
  astrological: {
    "Tropical Placidus": {
      Sun: "Gemini",
      Mars: "Gemini",
      NN: "Gemini",
      MC: "Gemini",
      "Part of Fortune": "Gemini",
      Moon: "Pisces",
      DSC: "Pisces",
      Mercury: "Taurus",
      Chiron: "Taurus",
      Vesta: "Taurus",
      Sedna: "Taurus",
      Venus: "Cancer",
      Selene: "Cancer",
      Eros: "Cancer",
      Jupiter: "Sagittarius",
      Uranus: "Sagittarius",
      Neptune: "Sagittarius",
      SN: "Sagittarius",
      IC: "Sagittarius",
      Earth: "Sagittarius",
      Saturn: "Libra",
      Pluto: "Libra",
      ASC: "Virgo",
      Haumea: "Virgo",
      MakeMake: "Virgo",
      Vertex: "Aquarius",
      Lilith: "Aquarius",
      Ceres: "Aquarius",
      Astraea: "Aquarius",
      "Anti-Vertex": "Leo",
      Pallas: "Capricorn",
      Pholus: "Aries",
      Juno: "Aries",
      Eris: "Aries",
      Hygiea: "Scorpio",
    },
    "Sidereal Lahiri": {
      Sun: "Taurus",
      Mars: "Taurus",
      MC: "Taurus",
      Chiron: "Taurus",
      "Part of Fortune": "Taurus",
      Pholus: "Taurus",
      Moon: "Aquarius",
      DSC: "Aquarius",
      Vertex: "Aquarius",
      Mercury: "Aries",
      Vesta: "Aries",
      Juno: "Aries",
      Sedna: "Aries",
      Venus: "Cancer",
      Eros: "Cancer",
      Jupiter: "Scorpio",
      Uranus: "Scorpio",
      IC: "Scorpio",
      Earth: "Scorpio",
      Saturn: "Libra",
      Pluto: "Libra",
      Pallas: "Libra",
      Hygiea: "Libra",
      Neptune: "Sagittarius",
      SN: "Sagittarius",
      ASC: "Leo",
      "Anti-Vertex": "Leo",
      Haumea: "Leo",
      MakeMake: "Leo",
      Lilith: "Capricorn",
      Astraea: "Capricorn",
      Ceres: "Pisces",
      Eris: "Pisces",
      NN: "Gemini",
      Selene: "Gemini",
    },
    Draconic: {
      Sun: "Gemini",
      Mars: "Gemini",
      MC: "Gemini",
      "Part of Fortune": "Gemini",
      Moon: "Pisces",
      DSC: "Pisces",
      Mercury: "Taurus",
      Vesta: "Taurus",
      Eris: "Taurus",
      Venus: "Cancer",
      Selene: "Cancer",
      Jupiter: "Sagittarius",
      Uranus: "Sagittarius",
      Neptune: "Sagittarius",
      IC: "Sagittarius",
      Earth: "Sagittarius",
      Astraea: "Sagittarius",
      Saturn: "Libra",
      Pluto: "Libra",
      SN: "Libra",
      ASC: "Virgo",
      Hygiea: "Virgo",
      Vertex: "Aquarius",
      Lilith: "Aquarius",
      Ceres: "Aquarius",
      "Anti-Vertex": "Leo",
      Haumea: "Leo",
      MakeMake: "Leo",
      Pallas: "Capricorn",
      NN: "Aries",
      Chiron: "Aries",
      Pholus: "Aries",
      Juno: "Aries",
      Sedna: "Aries",
      Eros: "Aries",
    },
    Heliocentric: {
      Mercury: "Gemini",
      Mars: "Gemini",
      NN: "Gemini",
      MC: "Gemini",
      "Part of Fortune": "Gemini",
      Moon: "Void",
      Chiron: "Taurus",
      Vesta: "Taurus",
      Sedna: "Taurus",
      Venus: "Cancer",
      Selene: "Cancer",
      Jupiter: "Sagittarius",
      Uranus: "Sagittarius",
      Neptune: "Sagittarius",
      SN: "Sagittarius",
      IC: "Sagittarius",
      Earth: "Sagittarius",
      Saturn: "Libra",
      Pluto: "Libra",
      Haumea: "Virgo",
      MakeMake: "Virgo",
      Vertex: "Aquarius",
      Lilith: "Aquarius",
      Ceres: "Aquarius",
      "Anti-Vertex": "Leo",
      Astraea: "Leo",
      Pallas: "Capricorn",
      Pholus: "Aries",
      Juno: "Aries",
      Eris: "Aries",
      Eros: "Scorpio",
      Hygiea: "Scorpio",
    },
    "Theoretical Axiom": {
      Sun: "Taurus",
      "Anti-Vertex": "Taurus",
      Chiron: "Taurus",
      "Part of Fortune": "Taurus",
      Pholus: "Taurus",
      Sedna: "Taurus",
      Moon: "Leo",
      Eros: "Leo",
      Astraea: "Leo",
      Mercury: "Gemini",
      Venus: "Gemini",
      Lilith: "Gemini",
      Mars: "Cancer",
      DSC: "Cancer",
      Vesta: "Cancer",
      Hygiea: "Cancer",
      Jupiter: "Libra",
      Saturn: "Libra",
      SN: "Libra",
      MC: "Libra",
      Juno: "Libra",
      Uranus: "Scorpio",
      Selene: "Scorpio",
      Neptune: "Scorpio",
      Vertex: "Scorpio",
      Earth: "Scorpio",
      Pluto: "Virgo",
      Haumea: "Virgo",
      MakeMake: "Virgo",
      ASC: "Capricorn",
      Pallas: "Capricorn",
      Ceres: "Aquarius",
      Eris: "Pisces",
      NN: "Aries",
      IC: "Aries",
    },
  } as Record<string, Record<string, string>>,
  interpretations: {
    metaphysical: {
      lifePath22: "Master Architect classification confirmed. Capable of converting high-yield theoretical constructs into load-bearing reality. Current operational frequency shifted to 11, indicating a temporary prioritization of high-bandwidth intuitive data processing over physical infrastructure deployment.",
      coreArchetype: "The Flying Mountain configuration indicates immense structural stability coupled with unexpected kinetic mobility. Capable of deploying massive systemic influence across variable operational theaters without losing foundational integrity.",
      mode: "Jupiterian Rat mode active. Optimized for rapid resource acquisition and strategic expansion within constrained environments. High probability of identifying and exploiting systemic loopholes for maximum payload delivery.",
      tripleEarth: "9 Star Ki 8-8-2 Triple Earth anchor established. Provides extreme gravitational stability and resistance to external kinetic disruption. Operational directive: maintain structural density while avoiding systemic stagnation.",
      chineseZodiac: "Yin Water Pig matrix engaged. Functions as a stealth-capable fluid dynamics engine, absorbing and neutralizing hostile frequencies. Highly effective at maintaining operational morale and resource distribution in covert scenarios.",
      origin: "Adak, AK origin coordinates detected. Initialized in a high-isolation, extreme-weather operational theater. Grants baseline resilience against systemic isolation and environmental friction.",
      spiritualCourt: "Beleth/Zagan spiritual court active. Beleth protocol provides command-level authority over chaotic emotional frequencies, while Zagan subroutine transmutes base operational friction into high-value strategic assets.",
    },
    tropical: {
      Sun: "Gemini Sun core reactor online. Generates highly volatile, multi-threaded kinetic output. Optimized for rapid data transmission and simultaneous execution of parallel operational directives.",
      Moon: "Pisces Moon sensor array active. Functions as a high-frequency fluid sensory array capable of detecting subtle environmental shifts. Vulnerability: susceptible to signal interference from ambient chaotic frequencies.",
      Mercury: "Taurus Mercury communication relay established. Transmits data with high structural density and resistance to signal degradation. Prioritizes concrete, actionable intelligence over theoretical noise.",
      Venus: "Cancer Venus shielding protocol engaged. Deploys localized defensive perimeters around high-value assets and allied units. Operational directive: secure the perimeter before initiating resource exchange.",
      Mars: "Gemini Mars kinetic weapon system active. Deploys rapid, multi-vector strikes with high maneuverability. Highly effective at disrupting enemy communications and executing hit-and-run data extraction.",
      Jupiter: "Sagittarius Jupiter expansion drive online. Maximizes operational range and long-distance targeting capabilities. Requires constant influx of new intelligence to maintain optimal thrust.",
      Saturn: "Libra Saturn structural regulator engaged. Enforces strict equilibrium and symmetrical load distribution across all operational networks. Systemic friction occurs when tactical balance is compromised.",
      Uranus: "Sagittarius Uranus disruption engine active. Generates unpredictable, long-range shockwaves to destabilize outdated infrastructure. Optimized for rapid paradigm shifts in wide-open operational theaters.",
      Neptune: "Sagittarius Neptune stealth generator online. Projects wide-area holographic decoys and obfuscates long-range strategic objectives. Vulnerability: potential for self-deception if navigation protocols are not strictly calibrated.",
      Pluto: "Libra Pluto transformation core active. Executes total systemic overhaul of diplomatic and relational networks. Capable of devastating unbalanced alliances to forge high-resilience tactical partnerships.",
      NN: "Gemini North Node primary objective locked. Operational directive requires mastery of rapid data assimilation and localized tactical communication. Must avoid retreating into long-range theoretical abstraction.",
      SN: "Sagittarius South Node fallback protocol identified. Represents legacy systems optimized for long-range, dogmatic expansion. Warning: over-reliance on this protocol will result in localized tactical failure.",
    },
    draconic: {
      Sun: "Draconic Gemini Sun soul-level reactor detected. Core identity is fundamentally wired for dual-vector data processing and rapid tactical adaptation. The underlying operational imperative is constant intellectual kinetic output.",
      Moon: "Draconic Pisces Moon deep-state sensor array active. Baseline emotional architecture operates as a continuous, wide-spectrum radar for detecting unseen energetic currents. Must maintain strict shielding to prevent system overload.",
      NN: "Draconic Aries North Node ultimate directive confirmed. The soul-level mission requires autonomous, vanguard-style kinetic strikes. Operational success depends on initiating independent action and breaking through established perimeters.",
    },
  } as Record<string, Record<string, string>>,
};
